# .readthedocs.yml

version: 2

python:
   version: 3.9
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
   system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py


formats:
    - epub
    - pdf
